### ISSUE TITLE
Wine tray 

### ISSUE THREAD

**Issue by popvladaurel** [MvBonin/wingpanel-community-indicators#5]
Hi! Can this be extended to include wine tray icons? Right now, if the application launched with wine comes with a tray icon, a new window small will pop-up "Wine System Tray" containing only that application's tray icon.

**Comment by MvBonin** [comment]
Hi :)
Currently we dont support Legacy icons ( Wine, PlayOnLinux ), but that would be nice.. 
If you wanted to implement it, you could make a pull request.
https://github.com/msmaldi/wingpanel-indicator-na-tray Lafydev had this in her README, Maybe this still works, but I didn't try it..

**Comment by popvladaurel** [comment]
Ty for that wingpanel-indicator-na-tray link. It works really well even in elementary OS 7, with a small dependency modification (wingpanel-2.0 changed to wingpanel). Battle.net tray icon now added to pantheon tray, instead of a new window; right-click menu shows up, all entries work.

![image](https://user-images.githubusercontent.com/23455688/224561458-06236895-6415-457c-a80d-1293d4ee430f.png)

I would not even know where to begin to implement it in this project though....
